name: Deploy Python functions to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - "lambda/**/lambda_function.py"
      - ".github/workflows/lambda_deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  # make sure this matches where your Lambdas live

      - name: Zip Lambda functions
        run: |
          cd lambda

          cd get_all_inventory_items
          zip -r ../../get_all_inventory_items.zip .
          cd ..

          cd get_inventory_item
          zip -r ../../get_inventory_item.zip .
          cd ..

          cd add_inventory_item
          zip -r ../../add_inventory_item.zip .
          cd ..

          cd delete_inventory_item
          zip -r ../../delete_inventory_item.zip .
          cd ..

          cd get_location_inventory_items
          zip -r ../../get_location_inventory_items.zip .
          cd ..

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name get_all_inventory_items \
            --zip-file fileb://get_all_inventory_items.zip \
            --publish

          aws lambda update-function-code \
            --function-name get_inventory_item \
            --zip-file fileb://get_inventory_item.zip \
            --publish

          aws lambda update-function-code \
            --function-name add_inventory_item \
            --zip-file fileb://add_inventory_item.zip \
            --publish

          aws lambda update-function-code \
            --function-name delete_inventory_item \
            --zip-file fileb://delete_inventory_item.zip \
            --publish

          aws lambda update-function-code \
            --function-name get_location_inventory_items \
            --zip-file fileb://get_location_inventory_items.zip \
            --publish
